const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];

const copy = {
  en:{tryNow:'Try now',eyebrow:'AI beauty & fashion for MENA',headline:'One mirror.<br><em>Two intelligent experiences.</em>',lead:'Understand your skin in detail, then explore a new look — powered by YouCam AI and designed for a seamless retail journey.',start:'Start your mirror',privacy:'Your API key never reaches the browser. Images are sent only through secure, temporary upload URLs.',experience:'THE MIRROR EXPERIENCE',choose:'Choose what you want to discover.',skinTab:'Skin Intelligence',styleTab:'Virtual Style',skinTitle:'See what your skin is saying.',skinText:'Upload a clear front-facing selfie. MirrorMENA analyzes wrinkles, pores, texture and acne using YouCam Skin Analysis v2.1.',skinTip1:'Face centered and looking straight ahead',skinTip2:'Bright, even lighting',skinTip3:'No filters or heavy occlusion',uploadSelfie:'Upload a selfie',jpgHint:'JPG or PNG · under 10 MB',analyze:'Analyze my skin',clothTitle:'Try the look before you wear it.',clothText:'Upload your photo and a garment reference. YouCam AI Clothes v3 generates a realistic virtual try-on while preserving your identity.',clothTip1:'Use a clear, front-facing person photo',clothTip2:'Use one garment or one outfit reference',clothTip3:'For best results, keep the body unobstructed',yourPhoto:'Your photo',personHint:'Front-facing',garment:'Garment',garmentHint:'Product or outfit',tryLook:'Create my try-on',proof1:'AI experiences in one retail journey',proof2:'Latest Skin Analysis endpoint',proof3:'AI Clothes virtual try-on engine',proof4:'API secrets exposed client-side',disclaimer:'Demo experience — not medical advice.'},
  ar:{tryNow:'جرّب الآن',eyebrow:'الجمال والأزياء بالذكاء الاصطناعي للمنطقة العربية',headline:'مرآة واحدة.<br><em>تجربتان ذكيتان.</em>',lead:'افهم بشرتك بتفاصيل أدق، ثم جرّب إطلالة جديدة — مدعوم بتقنيات YouCam AI ومصمم لتجربة تسوق سلسة.',start:'ابدأ تجربتك',privacy:'مفتاح API لا يصل إلى المتصفح. تُرسل الصور فقط عبر روابط رفع مؤقتة وآمنة.',experience:'تجربة المرآة',choose:'اختر ما تريد اكتشافه.',skinTab:'تحليل البشرة',styleTab:'تجربة الأزياء',skinTitle:'اكتشف ما تقوله بشرتك.',skinText:'ارفع صورة أمامية واضحة. يحلل MirrorMENA التجاعيد والمسام والملمس وحب الشباب عبر YouCam Skin Analysis v2.1.',skinTip1:'الوجه في المنتصف والنظر للأمام',skinTip2:'إضاءة واضحة ومتوازنة',skinTip3:'بدون فلاتر أو تغطية للوجه',uploadSelfie:'ارفع صورة للوجه',jpgHint:'JPG أو PNG · أقل من 10 MB',analyze:'حلّل بشرتي',clothTitle:'جرّب الإطلالة قبل ارتدائها.',clothText:'ارفع صورتك وصورة للقطعة. ينشئ YouCam AI Clothes v3 تجربة افتراضية واقعية للملابس.',clothTip1:'استخدم صورة واضحة ومواجهة للأمام',clothTip2:'استخدم قطعة واحدة أو إطلالة مرجعية واحدة',clothTip3:'لأفضل نتيجة اجعل الجسم واضحًا',yourPhoto:'صورتك',personHint:'مواجهة للأمام',garment:'القطعة',garmentHint:'منتج أو إطلالة',tryLook:'أنشئ تجربتي',proof1:'تجربتان بالذكاء الاصطناعي في رحلة واحدة',proof2:'أحدث إصدار لتحليل البشرة',proof3:'محرك تجربة الملابس الافتراضية',proof4:'أسرار API مكشوفة في المتصفح',disclaimer:'تجربة توضيحية — وليست نصيحة طبية.'}
};

let lang='en';
$('#langBtn').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('#langBtn').textContent=lang==='en'?'العربية':'English';$$('[data-i18n]').forEach(el=>{const v=copy[lang][el.dataset.i18n];if(v)el.innerHTML=v;});});

$$('.tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===btn));$$('.panel').forEach(x=>x.classList.remove('active'));$(`#panel-${btn.dataset.tab}`).classList.add('active');}));

function showPreview(input, img){const file=input.files?.[0];if(!file)return; if(file.size>=10*1024*1024){alert('Image must be under 10 MB.');input.value='';return;}img.src=URL.createObjectURL(file);img.hidden=false;updateButtons();}
['skin','person','garment'].forEach(name=>{const input=$(`#${name}File`),preview=$(`#${name}Preview`);input.addEventListener('change',()=>showPreview(input,preview));});
function updateButtons(){ $('#skinRun').disabled=!$('#skinFile').files?.[0]; $('#clothRun').disabled=!($('#personFile').files?.[0]&&$('#garmentFile').files?.[0]); }

function setStatus(id,text,type=''){const el=$(id);el.hidden=false;el.className=`status ${type}`;el.textContent=text;}
function clearResult(id){const el=$(id);el.hidden=true;el.innerHTML='';}
function getApiData(raw){return raw?.data?.data || raw?.data || raw;}
function extractTaskId(raw){const d=getApiData(raw);return d?.task_id || d?.data?.task_id;}
function extractTaskPayload(raw){return getApiData(raw);}

async function api(body){const r=await fetch('/api/youcam',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Request failed');return j;}
async function apiGet(action,taskId){const r=await fetch(`/api/youcam?action=${encodeURIComponent(action)}&task_id=${encodeURIComponent(taskId)}`,{cache:'no-store'});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Request failed');return j;}

function meta(file){let type=file.type;if(type==='image/jpeg')type='image/jpg';return{file_name:file.name,file_size:file.size,content_type:type};}
async function uploadFiles(feature,files){const prep=await api({action:'prepare-upload',feature,files:files.map(meta)});const root=getApiData(prep);const records=root?.files || root?.data?.files;if(!Array.isArray(records)||records.length!==files.length)throw new Error('Upload preparation returned an unexpected response.');for(let i=0;i<records.length;i++){const req=records[i]?.requests?.[0];if(!req?.url)throw new Error('Missing secure upload URL.');const headers={...(req.headers||{})};delete headers['Content-Length'];delete headers['content-length'];const put=await fetch(req.url,{method:req.method||'PUT',headers,body:files[i]});if(!put.ok)throw new Error(`Image upload failed (${put.status}).`);}return records.map(x=>x.file_id);}

async function poll(action,taskId,onTick,limit=90){for(let i=0;i<limit;i++){const raw=await apiGet(action,taskId);const d=extractTaskPayload(raw);const status=d?.task_status || d?.data?.task_status;if(status==='success')return d;if(status==='error')throw new Error(d?.error?.message||d?.error||'YouCam processing failed.');onTick?.(i+1,status||'processing');await new Promise(r=>setTimeout(r,2000));}throw new Error('Processing took too long. Please try again.');}

function flattenMetrics(obj,out=[],prefix=''){if(!obj||typeof obj!=='object'||out.length>16)return out;for(const [k,v] of Object.entries(obj)){const key=prefix?`${prefix}.${k}`:k;if(typeof v==='number'||typeof v==='string'&&v.length<50){if(/score|severity|value|level|grade/i.test(k))out.push([key,v]);}else if(v&&typeof v==='object'&&!Array.isArray(v))flattenMetrics(v,out,key);}return out;}
function findImages(obj,found=[]){if(!obj||typeof obj!=='object'||found.length>12)return found;for(const v of Object.values(obj)){if(typeof v==='string'&&/^https?:\/\//.test(v)&&/\.(png|jpe?g|webp)(\?|$)/i.test(v))found.push(v);else if(v&&typeof v==='object')findImages(v,found);}return [...new Set(found)];}

$('#skinRun').addEventListener('click',async()=>{const btn=$('#skinRun'),file=$('#skinFile').files[0];btn.disabled=true;clearResult('#skinResult');try{setStatus('#skinStatus','Preparing secure upload…');const [fileId]=await uploadFiles('skin',[file]);setStatus('#skinStatus','Starting YouCam Skin Analysis v2.1…');const started=await api({action:'start-skin',src_file_id:fileId});const taskId=extractTaskId(started);if(!taskId)throw new Error('YouCam did not return a task ID.');const done=await poll('skin-status',taskId,(n)=>setStatus('#skinStatus',`Analyzing skin… ${n}`));setStatus('#skinStatus','Analysis complete.','success');const result=$('#skinResult');const metrics=flattenMetrics(done);const images=findImages(done);result.innerHTML=`<div class="result-grid">${metrics.slice(0,8).map(([k,v])=>`<div class="metric"><b>${k.replaceAll('_',' ')}</b><span>${v}</span></div>`).join('')}</div>${images.slice(0,4).map(u=>`<img src="${u}" alt="Skin analysis result" style="margin-top:10px">`).join('')}${!metrics.length&&!images.length?`<pre>${escapeHtml(JSON.stringify(done,null,2))}</pre>`:''}`;result.hidden=false;}catch(e){setStatus('#skinStatus',e.message,'error');}finally{btn.disabled=false;}});

$('#clothRun').addEventListener('click',async()=>{const btn=$('#clothRun'),person=$('#personFile').files[0],garment=$('#garmentFile').files[0];btn.disabled=true;clearResult('#clothResult');try{setStatus('#clothStatus','Preparing secure uploads…');const [srcId,refId]=await uploadFiles('cloth',[person,garment]);setStatus('#clothStatus','Starting YouCam AI Clothes v3…');const started=await api({action:'start-cloth',src_file_id:srcId,ref_file_id:refId});const taskId=extractTaskId(started);if(!taskId)throw new Error('YouCam did not return a task ID.');const done=await poll('cloth-status',taskId,(n)=>setStatus('#clothStatus',`Creating virtual try-on… ${n}`));setStatus('#clothStatus','Your virtual try-on is ready.','success');const urls=findImages(done);const direct=done?.results?.url||done?.data?.results?.url;if(direct&&!urls.includes(direct))urls.unshift(direct);const result=$('#clothResult');result.innerHTML=urls.length?urls.slice(0,2).map(u=>`<img src="${u}" alt="Virtual try-on result">`).join(''):`<pre>${escapeHtml(JSON.stringify(done,null,2))}</pre>`;result.hidden=false;}catch(e){setStatus('#clothStatus',e.message,'error');}finally{btn.disabled=false;}});

function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
