import { createHash, randomUUID } from 'node:crypto';
import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { context, createServer, getServerPort, redis, reddit } from '@devvit/web/server';
import type { OnAppInstallRequest, TriggerResponse } from '@devvit/web/shared';

type Status='OPEN'|'CLAIMED'|'TESTING'|'SHIPPED';
type RequestRecord={id:string;title:string;problem:string;outcome:string;sourceUrl?:string;createdAt:string;createdBy:string;status:Status;builders:string[];builderKeys:string[];prototypeUrl?:string};
const app=new Hono();
const INDEX='requests:index'; const HUB='hub:post';
const h=(v:string)=>createHash('sha256').update(v).digest('hex').slice(0,24);
const viewer=()=>{if(!context.userId)throw new Error('Log in to Reddit to use this action.');return {key:h(context.userId),name:context.username||'redditor'}};
const clean=(x:unknown,max=500)=>String(x??'').trim().slice(0,max);
const readIndex=async()=>{try{return JSON.parse((await redis.get(INDEX))||'[]') as string[]}catch{return []}};
const writeIndex=(ids:string[])=>redis.set(INDEX,JSON.stringify(ids.slice(-500)));
const getReq=async(id:string)=>{const x=await redis.get(`req:${id}`);return x?JSON.parse(x) as RequestRecord:null};
const putReq=(r:RequestRecord)=>redis.set(`req:${r.id}`,JSON.stringify(r));
const count=async(k:string)=>Number.parseInt((await redis.get(k))||'0',10)||0;
const tokens=(s:string)=>new Set(s.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2&&!['the','and','for','with','this','that','need','want','tool','app'].includes(x)));
const similarity=(a:string,b:string)=>{const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/(A.size+B.size-n)};
async function support(id:string){const v=viewer();const k=`support:${id}:${v.key}`;if(await redis.get(k))return false;await redis.set(k,'1');await redis.incrBy(`count:support:${id}`,1);return true}
async function createOrMatch(input:{title:string;problem:string;outcome:string;sourceUrl?:string}){const v=viewer();const ids=await readIndex();for(const id of ids.slice(-80).reverse()){const r=await getReq(id);if(r&&r.status!=='SHIPPED'&&similarity(r.title,input.title)>=.72){await support(r.id);return {record:r,matched:true}}}const r:RequestRecord={id:randomUUID().slice(0,12),title:clean(input.title,120),problem:clean(input.problem,700),outcome:clean(input.outcome,500),sourceUrl:input.sourceUrl,createdAt:new Date().toISOString(),createdBy:v.name,status:'OPEN',builders:[],builderKeys:[]};if(!r.title||!r.problem||!r.outcome)throw new Error('Title, problem, and successful outcome are required.');await putReq(r);ids.push(r.id);await writeIndex(ids);await support(r.id);return {record:r,matched:false}}
async function createHub(){if(!context.subredditName)throw new Error('Missing subreddit context');const p=await reddit.submitCustomPost({subredditName:context.subredditName,title:'BUILD THIS — what should the internet build next?',entry:'default',textFallback:'Turn real Reddit problems into ranked demand, then connect them with developers who can build and testers who asked for the solution.'});await redis.set(HUB,p.id);return p}
async function hubPost(){const id=await redis.get(HUB);return id?reddit.getPostById(id):null}

app.get('/api/feed',async c=>{const ids=(await readIndex()).slice(-120);const v=context.userId?{key:h(context.userId)}:null;const items=(await Promise.all(ids.map(async id=>{const r=await getReq(id);if(!r)return null;const [supporters,testers,works,needsWork,viewerSupported,viewerTester]=await Promise.all([count(`count:support:${id}`),count(`count:tester:${id}`),count(`count:works:${id}`),count(`count:needs:${id}`),v?redis.get(`support:${id}:${v.key}`):null,v?redis.get(`tester:${id}:${v.key}`):null]);return {...r,supporters,testers,works,needsWork,viewerSupported:Boolean(viewerSupported),viewerTester:Boolean(viewerTester),viewerBuilder:Boolean(v&&r.builderKeys.includes(v.key))}}))).filter(Boolean) as any[];items.sort((a,b)=>{if(a.status==='SHIPPED'&&b.status!=='SHIPPED')return 1;if(b.status==='SHIPPED'&&a.status!=='SHIPPED')return -1;return b.supporters-a.supporters||Date.parse(b.createdAt)-Date.parse(a.createdAt)});return c.json({subredditName:context.subredditName||'community',open:items.filter(x=>x.status!=='SHIPPED').length,shipped:items.filter(x=>x.status==='SHIPPED').length,items})});
app.post('/api/requests',async c=>{try{const body=await c.req.json<any>();return c.json(await createOrMatch({title:clean(body.title,120),problem:clean(body.problem,700),outcome:clean(body.outcome,500)}))}catch(e){return c.json({message:e instanceof Error?e.message:'Could not create request'},400)}});
app.post('/api/requests/:id/support',async c=>{try{const r=await getReq(c.req.param('id'));if(!r)return c.json({message:'Request not found'},404);return c.json({added:await support(r.id)})}catch(e){return c.json({message:e instanceof Error?e.message:'Could not support'},400)}});
app.post('/api/requests/:id/tester',async c=>{try{const v=viewer(),id=c.req.param('id');if(!await getReq(id))return c.json({message:'Request not found'},404);const k=`tester:${id}:${v.key}`;if(!await redis.get(k)){await redis.set(k,'1');await redis.incrBy(`count:tester:${id}`,1)}return c.json({ok:true})}catch(e){return c.json({message:e instanceof Error?e.message:'Could not join beta'},400)}});
app.post('/api/requests/:id/claim',async c=>{try{const v=viewer(),id=c.req.param('id'),r=await getReq(id);if(!r)return c.json({message:'Request not found'},404);if(r.status==='SHIPPED')return c.json({message:'This request is already shipped.'},409);if(!r.builderKeys.includes(v.key)){if(r.builders.length>=3)return c.json({message:'This build already has three active builders.'},409);r.builders.push(v.name);r.builderKeys.push(v.key);if(r.status==='OPEN')r.status='CLAIMED';await putReq(r)}return c.json({ok:true})}catch(e){return c.json({message:e instanceof Error?e.message:'Could not claim'},400)}});
app.post('/api/requests/:id/prototype',async c=>{try{const v=viewer(),id=c.req.param('id'),r=await getReq(id);if(!r)return c.json({message:'Request not found'},404);if(!r.builderKeys.includes(v.key))return c.json({message:'Only a claimed builder can attach a prototype.'},403);const body=await c.req.json<any>();const url=clean(body.url,500);if(!/^https:\/\//i.test(url))return c.json({message:'Use a public https:// prototype URL.'},400);r.prototypeUrl=url;r.status='TESTING';await putReq(r);return c.json({ok:true})}catch(e){return c.json({message:e instanceof Error?e.message:'Could not add prototype'},400)}});
app.post('/api/requests/:id/vote',async c=>{try{const v=viewer(),id=c.req.param('id'),r=await getReq(id);if(!r?.prototypeUrl)return c.json({message:'No prototype is ready to test.'},409);const body=await c.req.json<any>();const vote=body.vote==='works'?'works':body.vote==='needs-work'?'needs':null;if(!vote)return c.json({message:'Invalid test result.'},400);const k=`vote:${id}:${v.key}`;if(await redis.get(k))return c.json({ok:true,duplicate:true});await redis.set(k,vote);await redis.incrBy(vote==='works'?`count:works:${id}`:`count:needs:${id}`,1);return c.json({ok:true})}catch(e){return c.json({message:e instanceof Error?e.message:'Could not record test'},400)}});
app.post('/api/requests/:id/ship',async c=>{try{const v=viewer(),id=c.req.param('id'),r=await getReq(id);if(!r)return c.json({message:'Request not found'},404);if(!r.builderKeys.includes(v.key))return c.json({message:'Only a claimed builder can mark this shipped.'},403);if(!r.prototypeUrl)return c.json({message:'Attach a working prototype first.'},409);r.status='SHIPPED';await putReq(r);return c.json({ok:true})}catch(e){return c.json({message:e instanceof Error?e.message:'Could not ship'},400)}});

app.post('/internal/menu/build-this',async c=>{try{await c.req.json().catch(()=>({}));if(!context.postId)return c.json({showToast:'Open the menu from a Reddit post.'});const p=await reddit.getPostById(context.postId);const out=await createOrMatch({title:p.title,problem:`People in r/${context.subredditName||'this community'} surfaced this need: ${p.title}`,outcome:'A usable solution that directly resolves the need described in the source post.',sourceUrl:p.permalink.startsWith('http')?p.permalink:`https://www.reddit.com${p.permalink}`});const hub=await hubPost();return c.json(hub?{showToast:out.matched?'Matched existing demand. Your vote was added.':'Build request created.',navigateTo:hub}:{showToast:out.matched?'Matched existing demand.':'Build request created. Open the BUILD THIS hub.'})}catch(e){return c.json({showToast:e instanceof Error?e.message:'Could not create build request.'})}});
app.post('/internal/menu/create-hub',async c=>{try{await c.req.json().catch(()=>({}));const p=await createHub();return c.json({showToast:'BUILD THIS hub created.',navigateTo:p})}catch(e){return c.json({showToast:e instanceof Error?e.message:'Could not create hub.'})}});
app.post('/internal/triggers/app-install',async c=>{try{await c.req.json<OnAppInstallRequest>();await createHub();return c.json<TriggerResponse>({status:'success',message:'BUILD THIS hub created'})}catch(e){console.error(e);return c.json<TriggerResponse>({status:'error',message:'Hub creation failed'},400)}});

serve({fetch:app.fetch,createServer,port:getServerPort()});
