import './styles.css';
import { createRoot } from 'react-dom/client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { navigateTo, showForm, showToast } from '@devvit/web/client';

type Status='OPEN'|'CLAIMED'|'TESTING'|'SHIPPED';
type Item={id:string;title:string;problem:string;outcome:string;sourceUrl?:string;createdAt:string;createdBy:string;status:Status;builders:string[];prototypeUrl?:string;supporters:number;testers:number;works:number;needsWork:number;viewerSupported:boolean;viewerTester:boolean;viewerBuilder:boolean};
type Feed={subredditName:string;open:number;shipped:number;items:Item[]};

async function api(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.message||`Request failed (${r.status})`);return j;}

function App(){
 const [data,setData]=useState<Feed|null>(null); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState<'ALL'|Status>('ALL');
 const load=useCallback(async()=>{setLoading(true);try{setData(await api('/api/feed'));}catch(e){showToast(e instanceof Error?e.message:'Could not load market');}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const items=useMemo(()=>data?.items.filter(i=>filter==='ALL'||i.status===filter)??[],[data,filter]);
 const createRequest=async()=>{const r=await showForm({form:{title:'Create a build request',description:'Describe a real problem, not a startup pitch.',fields:[{type:'string',name:'title',label:'Short request title',required:true},{type:'paragraph',name:'problem',label:'What problem needs solving?',required:true},{type:'paragraph',name:'outcome',label:'What would a successful solution do?',required:true}]}});if(!r)return;try{const out=await api('/api/requests',{title:r.title,problem:r.problem,outcome:r.outcome});showToast(out.matched?'Matched existing demand — your vote was added.':'Build request created.');await load()}catch(e){showToast(e instanceof Error?e.message:'Could not create request')}};
 const act=async(path:string,body?:unknown,msg?:string)=>{try{await api(path,body??{});if(msg)showToast(msg);await load()}catch(e){showToast(e instanceof Error?e.message:'Action failed')}};
 const addPrototype=async(i:Item)=>{const r=await showForm({form:{title:'Prototype ready',description:'Add a public URL where supporters can test what you built.',fields:[{type:'string',name:'url',label:'Prototype URL',required:true}]}});if(r?.url)await act(`/api/requests/${i.id}/prototype`,{url:r.url},'Prototype attached. Testers can open it now.')};
 return <main className="shell"><section className="hero"><div className="eyebrow">r/{data?.subredditName??'community'} · DEMAND SIGNAL</div><h1>BUILD THIS</h1><p>Real problems become ranked demand. Developers build what people already asked for.</p><button className="primary" onClick={createRequest}>+ CREATE BUILD REQUEST</button></section>
 <section className="metrics"><div><strong>{data?.open??0}</strong><span>active requests</span></div><div><strong>{data?.shipped??0}</strong><span>shipped solutions</span></div><div><strong>{data?.items.reduce((n,x)=>n+x.supporters,0)??0}</strong><span>demand votes</span></div></section>
 <nav className="filters">{(['ALL','OPEN','CLAIMED','TESTING','SHIPPED'] as const).map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</nav>
 {loading&&!data?<div className="loading">Loading live demand…</div>:<section className="grid">{items.map((i,rank)=><article className="card" key={i.id}><div className="topline"><span className="rank">#{rank+1}</span><span className={`status ${i.status.toLowerCase()}`}>{i.status}</span></div><h2>{i.title}</h2><p className="problem">{i.problem}</p><div className="outcome"><b>SUCCESS LOOKS LIKE</b><span>{i.outcome}</span></div><div className="numbers"><div><strong>{i.supporters}</strong><span>need this</span></div><div><strong>{i.testers}</strong><span>testers</span></div><div><strong>{i.builders.length}</strong><span>builders</span></div></div>{i.builders.length>0?<div className="builders">Building: {i.builders.map(x=>'u/'+x).join(', ')}</div>:null}
 <div className="actions"><button className={i.viewerSupported?'done':''} onClick={()=>act(`/api/requests/${i.id}/support`,{},i.viewerSupported?'Already counted.':'Demand +1')}>{i.viewerSupported?'✓ I NEED THIS':'I NEED THIS TOO'}</button><button className={i.viewerTester?'done':''} onClick={()=>act(`/api/requests/${i.id}/tester`,{},'You are in the beta pool.')}>{i.viewerTester?'✓ BETA TESTER':'I CAN TEST'}</button>{i.status!=='SHIPPED'&&!i.viewerBuilder?<button onClick={()=>act(`/api/requests/${i.id}/claim`,{},'Build claimed.')}>I’M BUILDING</button>:null}{i.viewerBuilder&&!i.prototypeUrl?<button onClick={()=>addPrototype(i)}>ADD PROTOTYPE</button>:null}{i.prototypeUrl?<button className="prototype" onClick={()=>navigateTo(i.prototypeUrl!)}>TEST PROTOTYPE ↗</button>:null}{i.prototypeUrl?<><button onClick={()=>act(`/api/requests/${i.id}/vote`,{vote:'works'},'Test recorded: works.')}>✓ WORKS {i.works}</button><button onClick={()=>act(`/api/requests/${i.id}/vote`,{vote:'needs-work'},'Test recorded: needs work.')}>NEEDS WORK {i.needsWork}</button></>:null}{i.viewerBuilder&&i.prototypeUrl&&i.status!=='SHIPPED'?<button className="ship" onClick={()=>act(`/api/requests/${i.id}/ship`,{},'Marked SHIPPED.')}>MARK SHIPPED</button>:null}{i.sourceUrl?<button className="ghost" onClick={()=>navigateTo(i.sourceUrl!)}>SOURCE POST ↗</button>:null}</div></article>)}</section>}
 <p className="foot">BUILD THIS stores only the minimum identity needed to prevent duplicate actions and show claimed builders. Demand starts from real Reddit posts or user-submitted problems.</p></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
